# Generated by Django 4.2.7 on 2024-01-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_message_mailing_mailing_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='send_to',
            new_name='client',
        ),
    ]
