# Generated by Django 4.2.7 on 2024-02-01 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0007_alter_mailing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Клиенты рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Сообщение'),
        ),
    ]
