# Generated by Django 4.2.7 on 2024-02-01 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_log_mailing_alter_mailing_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_point',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Начать рассылку'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop_point',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Завершить рассылку'),
        ),
    ]
